### ISSUE TITLE
Transfer of vehicles?

### ISSUE THREAD

**Issue by Supremeeeeeee** [LukeWasTakenn/luke_vehiclegarage#21]
Hey man, big fan of the garage script one of the best imo, so basically adding in a transfer vehicle option since you have it running by garage labels now, i have managed to add in a menu operated by the F5 menu (https://i.imgur.com/0esMWIe.jpeg) which makes a check for owned vehicles in the owned_vehicles database (simple so far) i then went on to add in a trigger for transfer but ive had no joy getting it to work, so you click on the plate you would like to transfer and this happens (https://i.imgur.com/a8QqOjd.jpeg) then when you click on 'Transfer Vehicle' a list of the garages show up (https://i.imgur.com/IFiKakY.jpeg) this is done by using the ' for k, v in pairs(Config.Garages) do ' then using v.GarageLabel to create the list , instead of adding each one indivisually, so whatever garages get added to the config update instantly on the list also, This is possible to happen id love to help in any way if its a future update man.

**Comment by LukeWasTakenn** [comment]
Doing a key, value pair loop is probably the best way of doing it, interesting idea though.

To be honest I don't really like the way the garages are done in the config file, I really want each garage to have an id and a label and store the id in the db because it's a lot simpler, also I don't want the garages to be keyed values in the config but rather just indexed because there's absolutely no point in having it keyed and I don't remember why I did it the way I did it currently. The difficult thing is changing it without actually breaking compatibility which I'm not sure how to do.

**Comment by Supremeeeeeee** [comment]
Yeah i got you man, i love the script its so smooth and the transfer vehicle being integrated would 100 percent make it a number 1 garage script. Imma keep trying to get it working and let you know the progress in time. Thanks for the quick response dude and taking time to answer! Have a wonderful day man

**Comment by Supremeeeeeee** [comment]
https://i.imgur.com/cWDn4Vd.png - client
https://i.imgur.com/t78JgaC.png - server

thats what i got so far, it picks up the garagelabel when trying to save to database but doesnt pick up the plate therefor it doesnt update the database, soons i find a way for it to pick up the plate to certain car, it should be done

**Comment by Supremeeeeeee** [comment]
ok dude, i done it! if you want the code for future update or to make it better lemme know man :) !

**Comment by LukeWasTakenn** [comment]
As I've said I'll probably be changing the config file and the way the garages are indexed, so I'll be adding my own implementation of it some time in the future. Thank you though.
