### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by colector-user** [LukeWasTakenn/luke_vehiclegarage#6]
when i take any car server crashed i use ESX Legacy

**Comment by colector-user** [comment]
ensure qtarget
ensure nh-context
ensure PolyZone
ensure luke_vehiclegarage

**Comment by LukeWasTakenn** [comment]
What server game build are you running?

**Comment by colector-user** [comment]
4394

**Comment by LukeWasTakenn** [comment]
Server game build, not your FiveM client version.

**Comment by colector-user** [comment]
where i found this idont know

**Comment by LukeWasTakenn** [comment]
In your server.cfg add `set sv_enforceGameBuild 2189`, this will force a newer game build on your server, you can change 2189 to 2060 for the Casino Heist DLC (2189 is Cayo Perico with the island) or 2372 for the latest tuners update.

Setting this will fix the issue.

**Comment by colector-user** [comment]
I will try Thank you For a quick answer

**Comment by colector-user** [comment]
its work fine but addon car is showing NULL

**Comment by LukeWasTakenn** [comment]
Read the main readme, I even provided an example of how to add custom cars, if even after following the example and your the custom vehicle doesn't work it's probably because it doesn't have a make or a model label assigned to it and I wouldn't know how to fix it. Closing this for now as the original issue is solved.
