### ISSUE TITLE
vector 3 or 4 

### ISSUE THREAD

**Issue by darknight2590** [LukeWasTakenn/luke_vehiclegarage#8]
Thank you for the beautiful code
But why not use vector 3 or 4  in code ?

**Comment by LukeWasTakenn** [comment]
I started and learned first with doing x,y,z tables so that kinda stuck to me and I never really bothered just using vector tables so that's why. You can also argue that x,y,z tables are a bit more easier to look at and figure out what's going on but switching to vector tables definitely wouldn't be bad
